### ISSUE TITLE
Add a variant that runs on root for ghcr.io/catthehacker/ubuntu:full-latest

### ISSUE THREAD

**Issue by NyaMisty** [catthehacker/docker_images#127]
Like `ghcr.io/catthehacker/ubuntu:act-*` and `ghcr.io/catthehacker/ubuntu:runner-*`, a full image with user `root` is also needed.

**Comment by ngarafol** [comment]
you could try modifying workflows like this:

`    runs-on: ubuntu-latest
     container:
       options: --user root`

` docker ps
CONTAINER ID   IMAGE                             COMMAND               CREATED          STATUS          PORTS     NAMES
59c07fb44830   catthehacker/ubuntu:full-latest   "tail -f /dev/null"   25 seconds ago   Up 23 seconds             act-Testing-test-4718f63292ac97c3f3d84f9e9cab0b220bd529eff2d82e44e5b5120482605a94`

`# docker exec -it 59c07fb44830 sh
# id
uid=0(root) gid=0(root) groups=0(root)`

This is what you asked, yes?

**Comment by catthehacker** [comment]
This can be easily implemented via custom image or Docker/Podman/etc. engine
