### ISSUE TITLE
no docker on full image?

### ISSUE THREAD

**Issue by orcutt989** [catthehacker/docker_images#18]
I just pulled the full image and I'm getting a docker daemon running error. Is docker not in the full image?

**Comment by catthehacker** [comment]
Did you mount the docker socket inside container?

**Comment by orcutt989** [comment]
No - is that something github does during a job? I was hoping to not have to add anything to replicate Github Actions 100% locally with Act. I'm hesitant to do extra stuff in the ci files just for local runs.

**Comment by catthehacker** [comment]
`act` will mount Docker socket automatically unless it's in unusual path or it fails somewhere, but if it fails, it's a problem with `act` and not an image

**Comment by orcutt989** [comment]
Oh perfect. Thanks for the followup!
