### ISSUE TITLE
Should js-* images work with act to run workflows with node actions?

### ISSUE THREAD

**Issue by flatiron32** [catthehacker/docker_images#30]
I have a workflow that calls an action that uses `node12`. When I attempt to run this workflow with act using either catthehacker/ubuntu:js-latest or catthehacker/ubuntu:act-latest I get 
```docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "node": executable file not found in $PATH: unknown.```
This is the same error I get when I run `docker run -it --rm ghcr.io/catthehacker/ubuntu:js-letest node`. Node is not in the path, but I think it needs to be for this to work.
I am sure I am missing something, what is it?

**Comment by catthehacker** [comment]
> This is the same error I get when I run `docker run -it --rm ghcr.io/catthehacker/ubuntu:js-letest node`.

standard behaviour since Docker is not invoking logon process that uses PAM module.



> I am sure I am missing something, what is it?

No idea since I don't know what are you trying to do. Paste your workflow or repository link.

**Comment by flatiron32** [comment]
Thank you for the quick response. I was expecting the `test` workflow like the one in this repo https://github.com/flatiron32/test-workflow to work and it was not. But as I was preparing this comment I updated ACT to make sure it was still a problem on the latest version and it is not. I am sorry for wasting your time. All is well with ACT 0.2.26 but was broken with 0.2.21.
Thank and sorry again.
