### ISSUE TITLE
`lchown /etc: no such file or directory`

### ISSUE THREAD

**Issue by Marvin-Brouwer** [catthehacker/docker_images#41]
I'm trying to install `act` on an Ubuntu-20.04 system but I get this when I try to pull the act docker image:

```txt
docker pull catthehacker/ubuntu:act-20.04
act-20.04: Pulling from catthehacker/ubuntu
7b1a6ab2e44d: Already exists
e5d2365e1e08: Extracting [==================================================>]  7.775MB/7.775MB
577c425bc292: Download complete
81fcda6c22ed: Download complete
91046370e281: Download complete
bada956823bf: Download complete
9a092865042a: Download complete
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /etc: no such file or directory
```
Any image I pull from this repo ends with `failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /etc: no such file or directory`.
I don't git this on a full ubuntu image.
I already did some googling and I couldn't really find anything interesting.

I did find this article however: https://stackoverflow.com/a/66017633/2319865.
It appears to be a docker issue with NFS, and it might be happening inside of the image on startup.

For context, I am running this inside of WSL2 on Windows 10 if it helps.

**Comment by catthehacker** [comment]
it's probably because `/etc/environment` is written during build

**Comment by catthehacker** [comment]
no idea

**Comment by Marvin-Brouwer** [comment]
I tried chmodding `/etc/environment` but it didn't help
I think this must be happening inside of the docker image.

**Comment by Marvin-Brouwer** [comment]
Could this maybe be related to: #1?
I'm storing my images on a `/mnt/d` drive which definitely has enough space but my main drive may not have enough to store the temp data?

**Comment by catthehacker** [comment]
Can't be fixed from my side as images/act depend on modified `/etc/environment`

**Comment by linbingdouzhe** [comment]
i think this is not issue for catthehacker repo only , maybe it's a docker bug 
on my case 
1.install docker
2.modify daemon.json to change the images drive
3.restart docker and pull a new image
4.the error lchown /etc: no such file or directory reported 

for now , I did not found any solution about this ...

**Comment by Marvin-Brouwer** [comment]
Hmm, perhaps you can try it with the default Daemon location?
I don't have the disk space to check that sadly.
