### ISSUE TITLE
Arm64 images

### ISSUE THREAD

**Issue by allexoll** [catthehacker/docker_images#50]
Would it be possible to publish similar images for arm64? It seems like your script would allow it pretty easily, and that would help a lot people running act on Arm macs.

**Comment by catthehacker** [comment]
It's already building arm64 and armhf images
https://github.com/catthehacker/docker_images/blob/664778dd40b1490023a0140d0e7ea6dc2f3a93f2/.github/workflows/build-ubuntu.yml#L42

**Comment by allexoll** [comment]
ah my bad, sorry for the issue!
